### ISSUE TITLE
Some sort of reorganizing??

### ISSUE THREAD

**Issue by Thunder33345** [piperun/iploggerfilter#22]
As of now: contributors just adds domains where they felt fit,
we should organize them into either:
- Sort by alphanumeric : basically all sites will now be sorted by their first alphabet
- Sort by "owned sites" : basically all sites will be categorized into owner site -> owned sites, and alphanumeric within it

Why?
Since right now the list is in disorganized sometimes some domains are grouped together, sometimes it isnt, there should be a standard for others to know what to expect in how this list should be structured

Personally i vouch for sort by "owned sites" to allow us to get a clearer picture(and less confusing to insert then alphanumeric), if you greenlight this i am happy to start reorganizing

**Comment by Thunder33345** [comment]
>but the issue I see is how would we find out about who owns which site

no not to mean as referring to real owner's name but as like "grabify.link" owned "discörd.com" which can be proven by them allowing you to use that link to track OR say when visited redirects to "grabify.link"

**Comment by piperun** [comment]
Ah, I see, I took a look at your repo and it seems to be well done, I prefer to have "dead links" in, in case they were to be used as an iplogger.

**Comment by Thunder33345** [comment]
yeah they are kept but well cant really attribute ownership so i made the "dead links"
i originally thought of removing but have the same fear

got it will pull pull changes latter
