### ISSUE TITLE
Adding goo.gl links

### ISSUE THREAD

**Issue by jLynx** [piperun/iploggerfilter#24]
You should add goo.gl, bit.ly, etc etc as they can all be used

**Comment by Thunder33345** [comment]
well, these sites do not "grab" user's ip
they only "mask" ip grabber

if you already blocked the ip grabber there's no need to block redirectors
as far as i know you cant get ips via goo.gl bit.ly etc, you can only get some approximate stats
we should consider moving away from blocking redirectors IMO

**Comment by jLynx** [comment]
Fair enough, Also on a side note, reply to me on twitter Thunder 🙂
