### ISSUE TITLE
*.appspot.com breaks virustotal

### ISSUE THREAD

**Issue by m0m0lepr0** [piperun/iploggerfilter#3]
The commit https://github.com/piperun/iploggerfilter/commit/7bedf265e77fcbbf9db59eab1dc848cd53de8a8e added *.appspot.com.
This change breaks virustotal which calls different files under https://virustotalcloud.appspot.com/static/

**Comment by piperun** [comment]
Thanks for the notification! Reverted back the change.

**Comment by riking** [comment]
appspot.com is a generic hosting domain, not dedicated to trackers :)

---

Anyone else having this issue, just force-update the lists from chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html

**Comment by piperun** [comment]
I see, didn't expect them to be using legitimate urls for their shady business.
