### ISSUE TITLE
Link Request

### ISSUE THREAD

**Issue by JaffaCakes118** [piperun/iploggerfilter#38]
Hey, this site here seems to be a website just dedicated to logging IP's - https://ctrlhub.co/iplogger
I believe you have some of their links already blacklisted.

Also- https://grabify.icu/

**Comment by piperun** [comment]
Hi!
Thanks for the issue!
You're correct we already got those specific domains which ctrlhub uses, however grabify.icu was new which has been added.

**Comment by JaffaCakes118** [comment]
Ok, thank you!
