### ISSUE TITLE
Add myprivate.pics

### ISSUE THREAD

**Issue by JaffaCakes118** [piperun/iploggerfilter#52]
![Screenshot_1](https://user-images.githubusercontent.com/50051038/180869790-d185eb1a-5c44-4ae4-958d-cbb9d62723da.png)

**Comment by spirillen** [comment]
Thanks for the report, I've "stolen" it, hoping you don't mind to much

- https://mypdns.org/my-privacy-dns/matrix/-/issues/967192
- https://mypdns.org/my-privacy-dns/matrix/-/issues/983927

**Comment by piperun** [comment]
Thanks for opening up the issue, the link has been added!
